### ISSUE TITLE
Add brief description to start of check_rasp_temp

### ISSUE THREAD

**Issue by JohnLines** [larsen0815/check_rasp_temp#1]
I have installed this on several systems running Raspbian Stretch, and it works well, with a monitoring server running Debian Icinga2.

It would be useful, for people who encounter this on their own system later to add a header line such as

`# check_rasp_temp - https://github.com/larsen0815/check_rasp_temp`

to find where it came from.

**Comment by larsen0815** [comment]
Have added a header line.
(Didn't see this issue till now)
