### ISSUE TITLE
Hardcoded location for vcgencmd; false negative

### ISSUE THREAD

**Issue by brucepleat** [larsen0815/check_rasp_temp#2]
Code is hardcoded to "/opt/vc/bin/vcgencmd"
Most of my Raspberry Pi configs (running Buster or Bullseye) have vcgencmd in "/usr/bin/vcgencmd"
Either the script should "which" to find it (and if not present, error!), or "find" where it is, or (least preferable) check both paths and use appropriate one.

Indicated above: if vcgencmd is not found, the response is "OK", despite whatever the temperature might be, a false "OK" (false negative).  For months I didn't realize and thought my Pis were alright...

**Comment by larsen0815** [comment]
Thanks for the report!
Fixed in commit da2be22

My one and only raspi is still using wheezy where "/usr/bin/vcgencmd" is a symlink to "/opt/vc/bin/vcgencmd".
